//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Language = new HashSet<Language>();
        }
    
        public int Id { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<Language> Language { get; set; }
    }
}
